import turtle # python needs this to use all the turtle functions
t2=turtle.Turtle()
turtle.speed(0)
turtle.shape('turtle') # changes the shape to a turtleturtle.
turtle.bgcolor("purple")
turtle.color("white")
turtle.penup()
turtle.goto(-100,0)
turtle.pendown()
turtle.goto(-100,150)
turtle.color("yellow")
turtle.goto(0,150)
turtle.goto(0,0)
turtle.pensize(5)
t2.speed(-200)
t2.penup()
t2.goto(100,0) 
t2.color("blue")
t2.pensize(6)
t2.pendown()
t2.goto(100,-150)
t2.color("green")
t2.goto(0,-150)
t2.goto(0,0)
